services:
  db:
    image: postgres:15-alpine
    container_name: web_scraper_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysequel1!
      POSTGRES_DB: web_scraper_chat_agent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web_scraper_backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:mysequel1!@db:5432/web_scraper_chat_agent
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_CLUSTER_ENDPOINT=${QDRANT_CLUSTER_ENDPOINT}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NGINX_CONFIG: nginx.conf
    container_name: web_scraper_frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    environment:
      - VITE_API_URL=http://3.106.249.0:8000

  widget:
    build:
      context: ./widget-sdk
      dockerfile: Dockerfile
    container_name: web_scraper_widget
    restart: always
    ports:
      - "8081:80"

  cal-backend:
    build:
      context: ./cal_backend
      dockerfile: Dockerfile
    container_name: web_scraper_cal_backend
    restart: always
    environment:
      - MAIN_BACKEND_URL=http://backend:8000
    env_file:
      - ./cal_backend/.env
    ports:
      - "8001:8001"

volumes:
  postgres_data:
